[build]
  base = "StackSurge-app" # Base directory for the app
  publish = "dist" # Frontend output directory
  functions = "backend" # Backend serverless functions directory

[build.environment]
  NODE_VERSION = "20"

[dev]
  framework = "vite" # Specify Vite as the framework for local dev
  command = "npm run dev" # Vite dev command for frontend
  targetPort = 5173 # Port where Vite serves the frontend
  port = 8888 # Proxy port for Netlify Dev

[functions]
directory = "backend"
included_files = [
  "backend/controllers/**",
  "backend/models/**",
  "backend/routes/**"
]
